apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: langflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: langflow.azurecr.io/langflow-backend:latest
        ports:
        - containerPort: 7860
        env:
        - name: REDIS_HOST
          value: redis
        - name: POSTGRES_HOST
          value: postgres
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: langflow-secrets
              key: database-url
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: langflow-secrets
              key: redis-password
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 7860
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 7860
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: acr-secret